//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Many2Many
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int ActorID { get; set; }
        public string ActorName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
