//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q3_ShowBalance.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Interface1")]
    public interface Interface1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Check_Balance", ReplyAction="http://tempuri.org/Interface1/Check_BalanceResponse")]
        string Check_Balance(int mobileNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Check_Balance", ReplyAction="http://tempuri.org/Interface1/Check_BalanceResponse")]
        System.Threading.Tasks.Task<string> Check_BalanceAsync(int mobileNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Check_Validity", ReplyAction="http://tempuri.org/Interface1/Check_ValidityResponse")]
        string Check_Validity(int mobileNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Check_Validity", ReplyAction="http://tempuri.org/Interface1/Check_ValidityResponse")]
        System.Threading.Tasks.Task<string> Check_ValidityAsync(int mobileNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Interface1Channel : Q3_ShowBalance.ServiceReference1.Interface1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Interface1Client : System.ServiceModel.ClientBase<Q3_ShowBalance.ServiceReference1.Interface1>, Q3_ShowBalance.ServiceReference1.Interface1 {
        
        public Interface1Client() {
        }
        
        public Interface1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Interface1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Interface1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Interface1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Check_Balance(int mobileNum) {
            return base.Channel.Check_Balance(mobileNum);
        }
        
        public System.Threading.Tasks.Task<string> Check_BalanceAsync(int mobileNum) {
            return base.Channel.Check_BalanceAsync(mobileNum);
        }
        
        public string Check_Validity(int mobileNum) {
            return base.Channel.Check_Validity(mobileNum);
        }
        
        public System.Threading.Tasks.Task<string> Check_ValidityAsync(int mobileNum) {
            return base.Channel.Check_ValidityAsync(mobileNum);
        }
    }
}
