//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class richEntities3 : DbContext
{
    public richEntities3()
        : base("name=richEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<iPhone> iPhones { get; set; }
    public DbSet<Mobile> Mobiles { get; set; }
    public DbSet<SmartPhone> SmartPhones { get; set; }
}
