//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class iPhone
{
    public int MobileID { get; set; }
    public string OperatingSystem { get; set; }

    public virtual Mobile Mobile { get; set; }
}

public partial class Mobile
{
    public int MobileID { get; set; }
    public string ModelNo { get; set; }
    public Nullable<int> Price { get; set; }

    public virtual iPhone iPhone { get; set; }
    public virtual SmartPhone SmartPhone { get; set; }
}

public partial class SmartPhone
{
    public int MobileID { get; set; }
    public string AndroidVer { get; set; }

    public virtual Mobile Mobile { get; set; }
}
