//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_Developer_Tester_TeamLead_ProjectManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tester : EmpQ2
    {
        public string ToolName { get; set; }
    }
}
