//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int CarDetailID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string BuyerName { get; set; }
        public Nullable<int> CarID { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
