//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class richEntities1 : DbContext
    {
        public richEntities1()
            : base("name=richEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Cars { get; set; }
    
        public virtual ObjectResult<proc101_Result> proc101()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc101_Result>("proc101");
        }
    
        public virtual ObjectResult<proc2_Result> proc2(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc2_Result>("proc2", cidParameter);
        }
    
        public virtual ObjectResult<proc101_Result> proc1011()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc101_Result>("proc1011");
        }
    
        public virtual ObjectResult<proc2_Result> proc21(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc2_Result>("proc21", cidParameter);
        }
    }
}
