//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneToOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> PersonAge { get; set; }
        public int PassportID { get; set; }
    
        public virtual Passport Passport { get; set; }
    }
}
