//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class News
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string NewHeadLine { get; set; }
        [DataMember]
        public string ReportName { get; set; }
        [DataMember]
        public string NewsDate { get; set; }
        [DataMember]
        public string NewsType { get; set; }
        [DataMember]
        public string NewsDescription { get; set; }
    }
}
