//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q3_Salary_Profile_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary", Namespace="http://schemas.datacontract.org/2004/07/Salary_Profile_Service")]
    [System.SerializableAttribute()]
    public partial class Salary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaryId {
            get {
                return this.SalaryIdField;
            }
            set {
                if ((this.SalaryIdField.Equals(value) != true)) {
                    this.SalaryIdField = value;
                    this.RaisePropertyChanged("SalaryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((this.TaxField.Equals(value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Salary_Profile_Service")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfileIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfileId {
            get {
                return this.ProfileIdField;
            }
            set {
                if ((this.ProfileIdField.Equals(value) != true)) {
                    this.ProfileIdField = value;
                    this.RaisePropertyChanged("ProfileId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyException", Namespace="http://schemas.datacontract.org/2004/07/Salary_Profile_Service")]
    [System.SerializableAttribute()]
    public partial class MyException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber {
            get {
                return this.LineNumberField;
            }
            set {
                if ((this.LineNumberField.Equals(value) != true)) {
                    this.LineNumberField = value;
                    this.RaisePropertyChanged("LineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISalary")]
    public interface ISalary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalary/GetSalary", ReplyAction="http://tempuri.org/ISalary/GetSalaryResponse")]
        Q3_Salary_Profile_Client.ServiceReference1.Salary GetSalary(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalary/GetSalary", ReplyAction="http://tempuri.org/ISalary/GetSalaryResponse")]
        System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Salary> GetSalaryAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalary/EditSalary", ReplyAction="http://tempuri.org/ISalary/EditSalaryResponse")]
        void EditSalary(int Id, Q3_Salary_Profile_Client.ServiceReference1.Salary salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalary/EditSalary", ReplyAction="http://tempuri.org/ISalary/EditSalaryResponse")]
        System.Threading.Tasks.Task EditSalaryAsync(int Id, Q3_Salary_Profile_Client.ServiceReference1.Salary salary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryChannel : Q3_Salary_Profile_Client.ServiceReference1.ISalary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryClient : System.ServiceModel.ClientBase<Q3_Salary_Profile_Client.ServiceReference1.ISalary>, Q3_Salary_Profile_Client.ServiceReference1.ISalary {
        
        public SalaryClient() {
        }
        
        public SalaryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Q3_Salary_Profile_Client.ServiceReference1.Salary GetSalary(int Id) {
            return base.Channel.GetSalary(Id);
        }
        
        public System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Salary> GetSalaryAsync(int Id) {
            return base.Channel.GetSalaryAsync(Id);
        }
        
        public void EditSalary(int Id, Q3_Salary_Profile_Client.ServiceReference1.Salary salary) {
            base.Channel.EditSalary(Id, salary);
        }
        
        public System.Threading.Tasks.Task EditSalaryAsync(int Id, Q3_Salary_Profile_Client.ServiceReference1.Salary salary) {
            return base.Channel.EditSalaryAsync(Id, salary);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProfile")]
    public interface IProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/GetAllProfile", ReplyAction="http://tempuri.org/IProfile/GetAllProfileResponse")]
        Q3_Salary_Profile_Client.ServiceReference1.Profile[] GetAllProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/GetAllProfile", ReplyAction="http://tempuri.org/IProfile/GetAllProfileResponse")]
        System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Profile[]> GetAllProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/GetProfileById", ReplyAction="http://tempuri.org/IProfile/GetProfileByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Q3_Salary_Profile_Client.ServiceReference1.MyException), Action="http://tempuri.org/IProfile/GetProfileByIdMyExceptionFault", Name="MyException", Namespace="http://schemas.datacontract.org/2004/07/Salary_Profile_Service")]
        Q3_Salary_Profile_Client.ServiceReference1.Profile GetProfileById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/GetProfileById", ReplyAction="http://tempuri.org/IProfile/GetProfileByIdResponse")]
        System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Profile> GetProfileByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/DeleteProfile", ReplyAction="http://tempuri.org/IProfile/DeleteProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Q3_Salary_Profile_Client.ServiceReference1.MyException), Action="http://tempuri.org/IProfile/DeleteProfileMyExceptionFault", Name="MyException", Namespace="http://schemas.datacontract.org/2004/07/Salary_Profile_Service")]
        void DeleteProfile(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/DeleteProfile", ReplyAction="http://tempuri.org/IProfile/DeleteProfileResponse")]
        System.Threading.Tasks.Task DeleteProfileAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/AddProfile", ReplyAction="http://tempuri.org/IProfile/AddProfileResponse")]
        void AddProfile(Q3_Salary_Profile_Client.ServiceReference1.Profile newProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfile/AddProfile", ReplyAction="http://tempuri.org/IProfile/AddProfileResponse")]
        System.Threading.Tasks.Task AddProfileAsync(Q3_Salary_Profile_Client.ServiceReference1.Profile newProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileChannel : Q3_Salary_Profile_Client.ServiceReference1.IProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileClient : System.ServiceModel.ClientBase<Q3_Salary_Profile_Client.ServiceReference1.IProfile>, Q3_Salary_Profile_Client.ServiceReference1.IProfile {
        
        public ProfileClient() {
        }
        
        public ProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Q3_Salary_Profile_Client.ServiceReference1.Profile[] GetAllProfile() {
            return base.Channel.GetAllProfile();
        }
        
        public System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Profile[]> GetAllProfileAsync() {
            return base.Channel.GetAllProfileAsync();
        }
        
        public Q3_Salary_Profile_Client.ServiceReference1.Profile GetProfileById(int Id) {
            return base.Channel.GetProfileById(Id);
        }
        
        public System.Threading.Tasks.Task<Q3_Salary_Profile_Client.ServiceReference1.Profile> GetProfileByIdAsync(int Id) {
            return base.Channel.GetProfileByIdAsync(Id);
        }
        
        public void DeleteProfile(int Id) {
            base.Channel.DeleteProfile(Id);
        }
        
        public System.Threading.Tasks.Task DeleteProfileAsync(int Id) {
            return base.Channel.DeleteProfileAsync(Id);
        }
        
        public void AddProfile(Q3_Salary_Profile_Client.ServiceReference1.Profile newProfile) {
            base.Channel.AddProfile(newProfile);
        }
        
        public System.Threading.Tasks.Task AddProfileAsync(Q3_Salary_Profile_Client.ServiceReference1.Profile newProfile) {
            return base.Channel.AddProfileAsync(newProfile);
        }
    }
}
