//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q3_Many_Many
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public Band()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int BandID { get; set; }
        public Nullable<int> Members { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
