//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q3_Many_Many
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Bands = new HashSet<Band>();
        }
    
        public int EventID { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<Band> Bands { get; set; }
    }
}
